// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MailWellDoneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver.exe");
    FirefoxProfile profile = new FirefoxProfile();
    FirefoxOptions options = new FirefoxOptions();
    options.setProfile(profile);
    driver = new FirefoxDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void MailWellDoneTest() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1358, 814));
    driver.findElement(By.id("mailbox:login-input")).click();
    driver.findElement(By.id("mailbox:login-input")).sendKeys("roman_gordeev11");
    driver.findElement(By.cssSelector(".mailbox__row_")).click();
    driver.findElement(By.id("mailbox:submit-button")).click();
    {
      WebElement element = driver.findElement(By.id("mailbox:submit-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mailbox:password-input")).sendKeys("a1097_A410");
    driver.findElement(By.id("mailbox:submit-button")).click();

    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    wait(3);
    driver.findElement(By.cssSelector(".compose-button__wrapper")).click();
    wait(3);
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".container--ItIg4 > .inputContainer--nsqFu > .container--H9L5q")).click();
    wait(3);
    driver.findElement(By.cssSelector(".letterYourselfIcon--sbIZ8")).click();
    wait(3);
    driver.findElement(By.cssSelector(".button2_primary .button2__txt")).click();
    wait(3);
    driver.findElement(By.cssSelector(".c2182")).click();
    wait(3);
    {
      WebElement element = driver.findElement(By.cssSelector(".llc:nth-child(10) .llc__content"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ico_16-close")).click();
    wait(3);
    driver.findElement(By.id("PH_logoutLink")).click();
  }
  public void wait(int seconds) {
    try {
      Thread.sleep(seconds * 1000);
    } catch (InterruptedException e) {
      throw new IllegalStateException(e);

    }
  }
}
